services:
  curious_file_upload.dropzone_type:
    class: CuriousInc\FileUploadFormTypeBundle\Form\Type\DropzoneType
    arguments:
      - '@oneup_uploader.templating.uploader_helper'
      - '@oneup_uploader.orphanage_manager'
      - '@doctrine.orm.entity_manager'
      - '@curious_file_upload.service.class_helper'
      - '@curious_file_upload.service.cache_helper'
      - '@curious_file_upload.file_namer'
      - '@request_stack'
    tags:
        - { name: form.type, alias: dropzone }

  curious_file_upload.twig.uploader_extension:
    class: CuriousInc\FileUploadFormTypeBundle\Twig\Extension\UploaderExtension
    arguments:
      - '@service_container'
      - '@oneup_uploader.orphanage_manager'
      - '@session'
      - '%oneup_uploader.orphanage%'
    tags:
        - { name: twig.extension }

  curious_file_upload.file_namer:
    class: CuriousInc\FileUploadFormTypeBundle\Namer\FileNamer

  curious_file_upload.service.cache_helper:
    class: CuriousInc\FileUploadFormTypeBundle\Service\CacheHelper
    arguments:
      - '@oneup_uploader.orphanage_manager'

  curious_file_upload.service.class_helper:
    class: CuriousInc\FileUploadFormTypeBundle\Service\ClassHelper
    arguments:
      - '@curious_file_upload.service.annotation_helper'

  curious_file_upload.service.annotation_helper:
    class: CuriousInc\FileUploadFormTypeBundle\Service\AnnotationHelper
    arguments:
      - '@?annotations.reader'

  curious_file_upload.migrator.media_bundle:
    class: CuriousInc\FileUploadFormTypeBundle\Migration\MediaBundleMigrator
    arguments:
      - '@service_container'
      - '@doctrine.orm.entity_manager'
      - '@curious_file_upload.file_namer'
      - '@curious_file_upload.service.annotation_helper'
      - '@curious_file_upload.service.class_helper'
